# Generated by Django 4.2 on 2023-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='MyBlog', max_length=255),
        ),
    ]
